/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alura.conversor.panels;

import com.alura.Temperatura.Temperaturas;
import com.alura.conversor.util.TemperaturasAgrupadas;
import javax.swing.JComboBox;

/**
 *
 * @author Usuario
 */
public class TemperaturaPanel extends javax.swing.JPanel {

    /**
     * Creates new form Temperatura
     */
    public TemperaturaPanel() {
        initComponents();
        InitContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        cboOption1 = new javax.swing.JComboBox<>();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        cboOption2 = new javax.swing.JComboBox<>();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 129, 61));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(880, 390));

        Content.setBackground(new java.awt.Color(185, 98, 80));
        Content.setToolTipText("");
        Content.setAlignmentX(0.0F);
        Content.setAlignmentY(0.0F);
        Content.setPreferredSize(new java.awt.Dimension(880, 390));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboOption1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOption1.setBorder(null);
        cboOption1.setPreferredSize(null);
        Content.add(cboOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 91, 140, 50));

        txtValor1.setBorder(null);
        txtValor1.setMinimumSize(new java.awt.Dimension(280, 50));
        txtValor1.setPreferredSize(new java.awt.Dimension(280, 50));
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValor1KeyReleased(evt);
            }
        });
        Content.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 91, -1, -1));

        txtValor2.setBorder(null);
        txtValor2.setPreferredSize(new java.awt.Dimension(280, 50));
        Content.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 261, -1, -1));

        btnCalcular.setBackground(new java.awt.Color(185, 61, 51));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outline_change_circle_white_36dp.png"))); // NOI18N
        btnCalcular.setBorder(null);
        btnCalcular.setBorderPainted(false);
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.setMaximumSize(new java.awt.Dimension(70, 46));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        Content.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 151, 100, 90));

        cboOption2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOption2.setBorder(null);
        cboOption2.setPreferredSize(null);
        Content.add(cboOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 261, 140, 50));

        Background.setBackground(new java.awt.Color(102, 255, 51));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0186835756733d0000000000000000000000000000018ae080e4f5.png@1280w_1l_2o_100sh.png"))); // NOI18N
        Background.setToolTipText("");
        Background.setAlignmentY(0.0F);
        Background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.setIconTextGap(0);
        Background.setMinimumSize(new java.awt.Dimension(880, 390));
        Background.setPreferredSize(new java.awt.Dimension(880, 390));
        Content.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
     String cbo1 =  cboOption1.getSelectedIndex()+"";
        String cbo2 = cboOption2.getSelectedIndex()+"";
        Change(cbo1, cbo2);
        TemperatureFunction();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtValor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyReleased

       TemperatureFunction();
    }//GEN-LAST:event_txtValor1KeyReleased

    private void InitContent() {
        cboTemperaturas(cboOption1);
        cboTemperaturas(cboOption2);

    }

    private void cboTemperaturas(JComboBox cbo) {
        cbo.removeAllItems();

        cbo.addItem("Seleccionar");
        for (Temperaturas temperaturas : Temperaturas.values()) {
            cbo.addItem(temperaturas.name());
        }
    }

    private void Change(String valor1, String valor2) {
        String temp = valor1;
        valor1 = valor2;
        valor2 = temp;

        cboOption1.setSelectedIndex(Integer.valueOf(valor1));
        cboOption2.setSelectedIndex(Integer.valueOf(valor2));
        System.out.println(valor1 + " " + valor2);
    }
    
    private void TemperatureFunction(){
     txtValor2.setText("");
        String valor1 = txtValor1.getText();
        String cbo1 = (String) cboOption1.getSelectedItem();
        String cbo2 = (String) cboOption2.getSelectedItem();
        //        System.out.println(cbo1 + cbo2);

        TemperaturasAgrupadas temperaturas = new TemperaturasAgrupadas();

        String resultado = temperaturas.OperaciónTemperatura(cbo1, cbo2, valor1);

        txtValor2.setText(resultado);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Content;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cboOption1;
    private javax.swing.JComboBox<String> cboOption2;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
